# must be unique in a given SonarQube Server instance
sonar.organization=davidch-03
sonar.projectKey=davidch-03_wakka-tattoes
sonar.sources= .
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
sonar.token=15370a31b6d9f58375a175812634b50d95679b17

# --- optional properties ---

# defaults to project key
#sonar.projectName=my project
# defaults to 'not provided'
#sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
#sonar.sources=.
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
#comando -> sonar-scanner.bat
# new code -> codigo generado
# overall code -> codigo general de todo el proyecto